CustomerFrontend/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CustomerFrontend.Models
{
    public class Customer
    {
        [DisplayName("Customer ID")]
        public int CustomerID { get; set; }

        [DisplayName("Customer Name")]
        [Required]
        public string CustomerName { get; set; } = string.Empty;

        [DisplayName("Customer Email")]
        [Required]
        [EmailAddress]
        public string CustomerEmail { get; set; }

        [DisplayName("Customer Phone")]
        [Required]
        [Phone]
        public string CustomerPhone { get; set; }

        [DisplayName("Date Added")]
        [DataType(DataType.Date)]
        public DateTime CreatedDate { get; set; }

        [DisplayName("Last Updated")]
        [DataType(DataType.Date)]
        public DateTime? UpdatedDate { get; set; }
    }
}

CustomerFrontend/Controllers/CustomerInteractionsController.cs
using CustomerFrontend.Models;
using CustomerFrontend.Services;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CustomerFrontend.Controllers
{
    public class CustomerInteractionsController : Controller
    {
        private readonly CustomerService _customerService;

        public CustomerInteractionsController()
        {
            _customerService = new CustomerService();
        }

        public async Task<ActionResult> Index(string sort, string searchString)
        {
            var customers = await _customerService.GetCustomersAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                customers = customers.Where(c => c.CustomerName.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sort)
            {
                case "id":
                    customers = customers.OrderBy(c => c.CustomerID).ToList(); 
                    break;
                case "name":
                    customers = customers.OrderBy(c => c.CustomerName).ToList();
                    break;
                case "email":
                    customers = customers.OrderBy(c => c.CustomerEmail).ToList();
                    break;
                case "phone":
                    customers = customers.OrderBy(c => c.CustomerPhone).ToList();
                    break;
                default:
                    customers = customers.OrderBy(c => c.CustomerID).ToList();
                    break;
            }

            return View(customers);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                var newCustomer = await _customerService.PostCustomer(customer);

                if (newCustomer.CustomerID != 0)
                    return RedirectToAction("Details", new { id = newCustomer.CustomerID });
            }

            return View(customer);
        }

        public async Task<ActionResult> Details(int id)
        {
            var customer = await _customerService.GetCustomerById(id);

            if (customer == null)
                return View("NotFound");

            return View(customer);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var customer = await _customerService.GetCustomerById(id);

            if (customer == null)
                return View("NotFound");

            return View(customer);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                var edit = await _customerService.PutCustomerEdit(customer);

                if (edit != null)
                    return RedirectToAction("Details", new { id = edit.CustomerID });
            }

            return View(customer);
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            var customer = await _customerService?.GetCustomerById(id);

            if (customer == null)
                return View("NotFound");

            return View(customer);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _customerService.DeleteCustomerById(id);
            return RedirectToAction("Index");
        }
    }
}

CustomerFrontend/Views/CustomerInteractions/Create.cshtml
@model CustomerFrontend.Models.Customer

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CustomerFrontend/Views/CustomerInteractions/Delete.cshtml
@model CustomerFrontend.Models.Customer

@{
    ViewBag.Title = "Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Customer?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CustomerFrontend/Views/CustomerInteractions/Details.cshtml
@model CustomerFrontend.Models.Customer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

@if (Model.CustomerID > 0)
{
    <div>
        <h4>Customer</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CustomerName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CustomerName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CustomerEmail)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CustomerEmail)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CustomerPhone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CustomerPhone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UpdatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UpdatedDate)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.CustomerID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
}
else
{
    <p class="alert alert-danger">Customer not found.</p>
}

CustomerFrontend/Views/CustomerInteractions/Edit.cshtml
@model CustomerFrontend.Models.Customer

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CustomerID)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CustomerFrontend/Views/CustomerInteractions/Index.cshtml
@model List<CustomerFrontend.Models.Customer>

@{
    ViewBag.Title = "Home Page";
}


<h2>Customers List</h2>

<div class="mt-2 mb-2">
    @Html.ActionLink("Create New Customer", "Create", null, new { @class = "mb-2" })
</div>

@using (Html.BeginForm())
{
    <div>
        <label class="form-label">Search by name</label>
        @Html.TextBox("SearchString", null, new { @class = "form-control mb-1" })
        <input type="submit" value="Search" class="btn btn-primary" />
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @if (Request.QueryString["sort"] == "id")
                {
                    <span>ID &#9650;</span>
                }
                else
                {
                    <a href="?sort=id">ID</a>
                }
            </th>
            <th>
                @if (Request.QueryString["sort"] == "name")
                {
                    <span>Name &#9650;</span>
                }
                else
                {
                    <a href="?sort=name">Name</a>
                }
            </th>
            <th>

                @if (Request.QueryString["sort"] == "email")
                {
                    <span>Email &#9650;</span>
                }
                else
                {
                    <a href="?sort=email">Email</a>
                }
            </th>
            <th>

                @if (Request.QueryString["sort"] == "phone")
                {
                    <span>Phone No. &#9650;</span>
                }
                else
                {
                    <a href="?sort=phone">Phone No.</a>
                }
            </th>
            <th>

                @if (Request.QueryString["sort"] == "date")
                {
                    <span>Date added &#9650;</span>
                }
                else
                {
                    <a href="?sort=date">Date added</a>
                }
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@customer.CustomerID</td>
                <td>@customer.CustomerName</td>
                <td>@customer.CustomerEmail</td>
                <td>@customer.CustomerPhone</td>
                <td>@customer.CreatedDate</td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = customer.CustomerID })
                    | @Html.ActionLink("Edit", "Edit", new { id = customer.CustomerID })
                    | @Html.ActionLink("Delete", "Delete", new { id = customer.CustomerID })
                </td>
            </tr>
        }
    </tbody>
</table>

CustomerFrontend/Views/CustomerInteractions/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>404 - Not Found</h2>
<p>The customer you are looking for does not exist.</p>
<a href="@Url.Action("Index", "CustomerInteractions")">Go back to the customer list</a>

CustomerFrontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Customer Viewer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Customer Viewer", "Index", "CustomerInteractions", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "CustomerInteractions", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Luke Brenton</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>